import {AIAutomationSession} from "./AIAutomationSession.sys.mjs";
import {GarpError,GarpErrorCode} from "../garp/GarpErrors.sys.mjs";
import {uuid} from "../garp/GarpUtil.sys.mjs";
function validateUrl(url){try{const u=new URL(url);if(!["http:","https:"].includes(u.protocol))throw 0}catch(_){throw new GarpError(GarpErrorCode.INVALID_ARGUMENT,"Only http:// and https:// URLs are permitted")}}
export class AIAutomationSessionManager{constructor(service,registry){this.service=service;this.registry=registry;this.sessions=new Map();this.tabIds=new WeakMap();this.tabsById=new Map()}
getTopWindow(){const w=this.service.getTopWindow();if(!w)throw new GarpError(GarpErrorCode.TAB_UNAVAILABLE,"No browser window available");return w}
getStableTabId(tab){if(!tab)throw new GarpError(GarpErrorCode.TAB_NOT_FOUND,"Tab unavailable");let id=this.tabIds.get(tab);if(!id){id=uuid();this.tabIds.set(tab,id)}this.tabsById.set(id,tab);return id}
resolveTab(id){const w=this.getTopWindow(),tab=this.tabsById.get(id);if(!tab||w.gBrowser.tabs.indexOf(tab)<0){if(tab)this.tabsById.delete(id);throw new GarpError(GarpErrorCode.TAB_NOT_FOUND,`Tab not found: ${id}`)}if(tab.linkedBrowser?.browsingContext?.discarded)throw new GarpError(GarpErrorCode.TAB_UNAVAILABLE,`Tab unavailable: ${id}`);return tab}
listTabs(){const w=this.getTopWindow();return w.gBrowser.tabs.map(tab=>({tab_id:this.getStableTabId(tab),url:tab.linkedBrowser?.currentURI?.spec||"about:blank",title:tab.label||"",active:!!tab.selected}))}
openTab(url){validateUrl(url);const w=this.getTopWindow();const tab=w.gBrowser.addTrustedTab(url);w.gBrowser.selectedTab=tab;return{tab_id:this.getStableTabId(tab),url}}
closeTab(id){const w=this.getTopWindow(),tab=this.resolveTab(id),tid=this.getStableTabId(tab);for(const s of this.sessions.values())if(s.tabId===tid)s.state="CLOSED";w.gBrowser.removeTab(tab);this.tabsById.delete(tid);return{success:true}}
selectTab(id){const w=this.getTopWindow(),tab=this.resolveTab(id);w.gBrowser.selectedTab=tab;return{success:true,tab_id:this.getStableTabId(tab)}}
createSession(provider,tabId=null){const a=this.registry.get(provider);if(!a)throw new GarpError(GarpErrorCode.PROVIDER_UNAVAILABLE,`Provider adapter unavailable: ${provider}`);let tab;if(tabId!==null)tab=this.resolveTab(tabId);else{const w=this.getTopWindow();tab=w.gBrowser.addTrustedTab(a.url);w.gBrowser.selectedTab=tab}const s=new AIAutomationSession({sessionId:uuid(),provider:a.name,tabId:this.getStableTabId(tab),pageGeneration:1n});s.state="PREPARING";s.pageURL=tab.linkedBrowser?.currentURI?.spec||"";this.sessions.set(s.sessionId,s);return s}
get(id){const s=this.sessions.get(id);if(!s)throw new GarpError(GarpErrorCode.SESSION_NOT_FOUND,`Session not found: ${id}`);if(s.state==="CLOSED")throw new GarpError(GarpErrorCode.SESSION_CLOSED,"Session is closed");return s}
attach(sid,connection){const s=this.get(sid);if(s.ownerConnection&&s.ownerConnection!==connection)throw new GarpError(GarpErrorCode.INVALID_MESSAGE_STATE,"Session already attached");s.ownerConnection=connection;s.subscribers.add(connection);return s}
detach(sid,connection){const s=this.get(sid);if(s.ownerConnection&&s.ownerConnection!==connection)throw new GarpError(GarpErrorCode.INVALID_MESSAGE_STATE,"Connection does not own session");s.ownerConnection=null;s.subscribers.delete(connection);return s}
closeSession(sid){const s=this.sessions.get(sid);if(!s)return null;s.state="CLOSED";s.activeRequestId=null;s.ownerConnection=null;s.subscribers.clear();s.actorObject=null;s.actorInstance=null;s.childActorInstance=null;return s}
resetSession(sid,connection){const s=this.get(sid);if(s.ownerConnection&&s.ownerConnection!==connection)throw new GarpError(GarpErrorCode.INVALID_MESSAGE_STATE,"Connection does not own session");s.assertMutable();s.state="PREPARING";s.inputState="UNKNOWN";s.generationState="IDLE";s.lastRequestId=null;s.lastMessageId=null;s.lastMessageText="";s.lastMessageCount=0;s.incrementPageGeneration(s.pageURL);return s}
getTabForSession(s){return this.resolveTab(s.tabId)}}
