unit Grisp.Types;

interface

uses
  System.SysUtils, System.Classes;

type
  /// <summary>
  /// Fail-closed candidate execution state machine states.
  /// </summary>
  TGrispCandidateState = (
    csCreated,
    csParsed,
    csCompiling,
    csCompiled,
    csTesting,
    csVerified,
    csRejected,
    csAccepted
  );

  /// <summary>
  /// Strict error categorization for parser and transport verification.
  /// </summary>
  TGrispErrorCode = (
    errNone,
    errParseAmbiguous,
    errParseError,
    errHashMismatch,
    errCompileFailed,
    errTestFailed,
    errTransportError
  );

  TGrispSessionID = TGuid;
  TGrispTabID = TGuid;

  /// <summary>
  /// Verifiable proof log entry generated by execution gates.
  /// </summary>
  TGrispEvidence = record
    Timestamp: TDateTime;
    Stage: TGrispCandidateState;
    Success: Boolean;
    ExitCode: Integer;
    OutputLog: string;
    ArtifactHash: string;
  end;

  /// <summary>
  /// Canonical byte payload and cryptographic checksum container.
  /// </summary>
  TGrispManifest = record
    SessionID: TGrispSessionID;
    TabID: TGrispTabID;
    SourcePath: string;
    ContentHash: string; // Hex-encoded SHA-256
    RawBytes: TBytes;    // Strict UTF-8 without BOM
  end;

  /// <summary>
  /// Primary tracked code artifact context.
  /// </summary>
  TGrispCandidate = record
    ID: TGrispSessionID;
    State: TGrispCandidateState;
    Manifest: TGrispManifest;
    EvidenceLog: TArray<TGrispEvidence>;
    LastError: TGrispErrorCode;
  end;

implementation

end.