export class GarpError extends Error {
    constructor(code, message, options = {}) {
        super(String(message || code));
        this.name = "GarpError";
        this.code = code;
        this.retryable = !!options.retryable;
        this.state = options.state ?? "ERROR";
        this.provider = options.provider ?? null;
        this.details = options.details ?? null;
        this.requestId = options.requestId ?? null;
        this.sessionId = options.sessionId ?? null;
        this.reason = options.reason ?? null;
    }
}

export const GarpErrorCode = Object.freeze({
    INVALID_ARGUMENT: "INVALID_ARGUMENT",
    INVALID_ENVELOPE: "INVALID_ENVELOPE",
    UNKNOWN_MESSAGE_TYPE: "UNKNOWN_MESSAGE_TYPE",
    UNKNOWN_MESSAGE_ID: "UNKNOWN_MESSAGE_ID",
    HEADER_JSON_MISMATCH: "HEADER_JSON_MISMATCH",
    UNSUPPORTED_VERSION: "UNSUPPORTED_VERSION",
    UNSUPPORTED_WIRE_VERSION: "UNSUPPORTED_WIRE_VERSION",
    UNSUPPORTED_FEATURE: "UNSUPPORTED_FEATURE",
    AUTH_REQUIRED: "AUTH_REQUIRED",
    AUTH_FAILED: "AUTH_FAILED",
    AUTH_REPLAY: "AUTH_REPLAY",
    HANDSHAKE_TIMEOUT: "HANDSHAKE_TIMEOUT",
    DUPLICATE_REQUEST: "DUPLICATE_REQUEST",
    REVISION_GAP: "REVISION_GAP",
    EVENT_SEQUENCE_GAP: "EVENT_SEQUENCE_GAP",
    EVENT_SEQUENCE_OVERFLOW: "EVENT_SEQUENCE_OVERFLOW",
    PAGE_GENERATION_OVERFLOW: "PAGE_GENERATION_OVERFLOW",
    INVALID_MESSAGE_STATE: "INVALID_MESSAGE_STATE",
    SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
    SESSION_CLOSED: "SESSION_CLOSED",
    SESSION_BUSY: "SESSION_BUSY",
    OUTSTANDING_REQUEST_LIMIT: "OUTSTANDING_REQUEST_LIMIT",
    TAB_NOT_FOUND: "TAB_NOT_FOUND",
    TAB_UNAVAILABLE: "TAB_UNAVAILABLE",
    PROMPT_NOT_FOUND: "PROMPT_NOT_FOUND",
    PROMPT_NOT_ACTIVE: "PROMPT_NOT_ACTIVE",
    PROMPT_ALREADY_TERMINAL: "PROMPT_ALREADY_TERMINAL",
    PROMPT_TIMEOUT: "PROMPT_TIMEOUT",
    PROMPT_CANCELLED: "PROMPT_CANCELLED",
    RESPONSE_NOT_READY: "RESPONSE_NOT_READY",
    INPUT_VERIFICATION_FAILED: "INPUT_VERIFICATION_FAILED",
    SUBMISSION_FAILED: "SUBMISSION_FAILED",
    STALE_ACTOR: "STALE_ACTOR",
    NAVIGATION_DRIFT: "NAVIGATION_DRIFT",
    PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
    PROVIDER_AUTH_REQUIRED: "PROVIDER_AUTH_REQUIRED",
    PROVIDER_RATE_LIMITED: "PROVIDER_RATE_LIMITED",
    PROVIDER_ERROR: "PROVIDER_ERROR",
    RESPONSE_TOO_LARGE: "RESPONSE_TOO_LARGE",
    GENERATION_BUFFER_LIMIT: "GENERATION_BUFFER_LIMIT",
    CONTINUATION_NOT_ALLOWED: "CONTINUATION_NOT_ALLOWED",
    CONTINUATION_LIMIT_REACHED: "CONTINUATION_LIMIT_REACHED",
    CONTINUATION_TIMEOUT: "CONTINUATION_TIMEOUT",
    CONTINUATION_NOT_AVAILABLE: "CONTINUATION_NOT_AVAILABLE",
    RECOVERY_FAILED: "RECOVERY_FAILED",
    EVENT_QUEUE_OVERFLOW: "EVENT_QUEUE_OVERFLOW",
    EVENT_HISTORY_EXPIRED: "EVENT_HISTORY_EXPIRED",
    FRAME_TOO_LARGE: "FRAME_TOO_LARGE",
    PROTOCOL_ERROR: "PROTOCOL_ERROR",
});
