export const GARP_PROTOCOL = "GARP/1.24";
export const GARP_SEMANTIC_VERSION = "1.24";
export const GARP_WIRE_VERSION = "0x00";
export const GARP_VERSION_BYTE = 0x00;
export const GARP_FIXED_HEADER_LENGTH = 48;
export const GARP_HANDSHAKE_LIMIT = 1024 * 1024;
export const GARP_APPLICATION_LIMIT_DEFAULT = 16 * 1024 * 1024;
export const GARP_UINT64_MAX = 18446744073709551615n;
export const GARP_HANDSHAKE_TIMEOUT_MS = 10000;
export const GARP_DEFAULT_RESPONSE_RETENTION_MS = 86400000n;
export const GARP_DEFAULT_CONTINUATION_WAIT_MS = 300000n;
export const GARP_DEFAULT_RECOVERY_DEADLINE_MS = 300000n;
export const GARP_DEFAULT_IDLE_TIMEOUT_MS = 30000n;
export const GARP_DEFAULT_INTERVAL_MS = 10000n;
export const GARP_MAX_PROMPT_SIZE = 1048576;
export const GARP_MAX_RESPONSE_SIZE = 16777216;
export const GARP_MAX_OUTSTANDING_REQUESTS = 128;
export const GARP_MAX_QUEUED_EVENTS = 8192;
export const GARP_MAX_EVENT_HISTORY_MEMORY_MB = 64;
export const GARP_MAX_GENERATION_BUFFER_MB = 32;
export const GARP_MAX_ERROR_DETAILS_BYTES = 65536;
export const GARP_MAX_DIAGNOSTIC_DETAILS_BYTES = 65536;

export const GarpMessageType = Object.freeze({
  HELLO: 0x0001, HELLO_CHALLENGE: 0x0002, HELLO_AUTH: 0x0003, HELLO_ACK: 0x0004, RESPONSE: 0x0005, ERROR: 0x0006,
  CAPABILITIES: 0x0010, BROWSER_STATUS: 0x0011, LIST_TABS: 0x0012, OPEN_TAB: 0x0013, CLOSE_TAB: 0x0014, SELECT_TAB: 0x0015, GET_CAPABILITIES: 0x0016,
  CREATE_SESSION: 0x0020, ATTACH_SESSION: 0x0021, DETACH_SESSION: 0x0022, CLOSE_SESSION: 0x0023, RESET_SESSION: 0x0024, GET_SESSION: 0x0025,
  PROMPT: 0x0030, CANCEL_PROMPT: 0x0031, GET_PROMPT_STATUS: 0x0032, GET_RESPONSE: 0x0033, SUBSCRIBE_RESPONSE: 0x0034, CONTINUE_PROMPT: 0x0035,
  SESSION_READY: 0x0040, SESSION_CHANGED: 0x0041, NAVIGATION: 0x0042, NAVIGATION_DRIFT: 0x0043, RECOVERY_STATE: 0x0044, PROVIDER_CHANGED: 0x0045,
  INPUT_SUBMITTED: 0x0050, GENERATION_STARTED: 0x0051, GENERATION_DELTA: 0x0052, GENERATION_PROGRESS: 0x0053, CONTINUATION_REQUIRED: 0x0054, CONTINUATION_SUBMITTED: 0x0055, GENERATION_COMPLETED: 0x0056, GENERATION_FAILED: 0x0057, GENERATION_CANCELLED: 0x0058,
  PROVIDER_ERROR: 0x0060, PROVIDER_AUTH_REQUIRED: 0x0061, PROVIDER_RATE_LIMITED: 0x0062, DIAGNOSTIC: 0x0063,
  PING: 0x0070, PONG: 0x0071, GET_EVENTS: 0x0100,
});
const TYPE_NAME_BY_ID = new Map(Object.entries(GarpMessageType).map(([name, id]) => [id, name]));
const TYPE_ID_BY_NAME = new Map(Object.entries(GarpMessageType).map(([name, id]) => [name, id]));
export function messageTypeName(id) { return TYPE_NAME_BY_ID.get(id) || null; }
export function messageTypeId(name) { return TYPE_ID_BY_NAME.get(String(name || "").toUpperCase()) || 0; }

export const GarpFeature = Object.freeze(["ext-pong", "ext-replay-store"]);
export const GarpSessionEventTypes = new Set(["SESSION_READY","SESSION_CHANGED","NAVIGATION","NAVIGATION_DRIFT","RECOVERY_STATE","PROVIDER_CHANGED","INPUT_SUBMITTED","GENERATION_STARTED","GENERATION_DELTA","GENERATION_PROGRESS","CONTINUATION_REQUIRED","CONTINUATION_SUBMITTED","GENERATION_COMPLETED","GENERATION_FAILED","GENERATION_CANCELLED","PROVIDER_ERROR","PROVIDER_AUTH_REQUIRED","PROVIDER_RATE_LIMITED","DIAGNOSTIC"]);
export const GarpConnectionScopedTypes = new Set(["HELLO","HELLO_CHALLENGE","HELLO_AUTH","HELLO_ACK","CAPABILITIES","BROWSER_STATUS","LIST_TABS","OPEN_TAB","CLOSE_TAB","SELECT_TAB","GET_CAPABILITIES","CREATE_SESSION","PING","PONG"]);
export const GarpSessionScopedCommandTypes = new Set(["ATTACH_SESSION","DETACH_SESSION","CLOSE_SESSION","RESET_SESSION","GET_SESSION","PROMPT","CANCEL_PROMPT","GET_PROMPT_STATUS","GET_RESPONSE","SUBSCRIBE_RESPONSE","CONTINUE_PROMPT","GET_EVENTS"]);
