export class GarpError extends Error {
  constructor(code, message, options = {}) {
    super(message);
    this.name = "GarpError";
    this.code = code;
    this.retryable = !!options.retryable;
    this.state = options.state || "ERROR";
    this.provider = options.provider || null;
    this.details = options.details || null;
  }
}

export const GarpErrorCode = Object.freeze({
  PROTOCOL_ERROR: "PROTOCOL_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FRAME_TOO_LARGE: "FRAME_TOO_LARGE",
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  TAB_NOT_FOUND: "TAB_NOT_FOUND",
  PROVIDER_NOT_FOUND: "PROVIDER_NOT_FOUND",
  SESSION_BUSY: "SESSION_BUSY",
  REQUEST_ID_REUSE: "REQUEST_ID_REUSE",
  DUPLICATE_REQUEST: "DUPLICATE_REQUEST",
  SEQUENCE_GAP: "SEQUENCE_GAP",
  SEQUENCE_CONFLICT: "SEQUENCE_CONFLICT",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  INPUT_NOT_READY: "INPUT_NOT_READY",
  SUBMIT_FAILED: "SUBMIT_FAILED",
  GENERATION_TIMEOUT: "GENERATION_TIMEOUT",
  GENERATION_FAILED: "GENERATION_FAILED",
  CONTINUATION_FAILED: "CONTINUATION_FAILED",
  NAVIGATION_CHANGED: "NAVIGATION_CHANGED",
  PROVIDER_RATE_LIMIT: "PROVIDER_RATE_LIMIT",
  DOM_UNSUPPORTED: "DOM_UNSUPPORTED",
  CANCELLED: "CANCELLED",
  RESPONSE_IDENTITY_UNKNOWN: "RESPONSE_IDENTITY_UNKNOWN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
});
